version: "3.5"
services:
  led:
    container_name: led
    build:
      context: ./container-led/
      dockerfile: Dockerfile
    volumes:
       - ./:/scr
    ports:
       - "80:80"
    restart: "always"
    privileged: true
    devices:
      - "/dev/i2c-1:/dev/i2c-1"

  button:
    container_name: button
    build:
      context: ./container-button/
      dockerfile: Dockerfile
    volumes:
       - ./:/scr
    restart: "always"
    privileged: true
    devices:
      - "/dev/i2c-1:/dev/i2c-1"





