version: "3.5"
services:
  led:
    container_name: led
    build:
      context: ./container-led/
      dockerfile: Dockerfile
    volumes:
       - ./:/scr
    ports:
       - "80:80"

  button:
    container_name: button
    build: 
      context: ./container-button/
      dockerfile: Dockerfile
    volumes:
       - ./:/scr

