trigger:
- main

pool:
  vmImage: ubuntu-18.04

variables:
  - group: "Latest Image Versions"

stages:
  #! Pre-build preparations
  - stage: Prebuild
    jobs:
      - job: envprep
        displayName: Preparation Steps
        steps:
          - template: ./tutorial-containers-03/.pipeline/templates/steps/pre-build.yml
            parameters:
              module: button
              latestVersion: $(button_latest)
              modulesPath: ./tutorial-containers-03/modules
          - template: ./tutorial-containers-03/.pipeline/templates/steps/pre-build.yml
            parameters:
              module: led
              latestVersion: $(led_latest)
              modulesPath: ./tutorial-containers-03/modules
