trigger:
- main

pool:
  vmImage: ubuntu-18.04

variables:
  - group: "Latest Image Versions"

stages:
  #! Pre-build preparations
  - stage: Prebuild
    jobs:
      - job: envprep
        displayName: Preparation Steps
        steps:
          - template: ./.pipeline/templates/steps/pre-build.yml
            parameters:
              module: button
              latestVersion: $(button_latest)
              modulesPath: tutorial-containers-03/modules
          - template: ./.pipeline/templates/steps/pre-build.yml
            parameters:
              module: led
              latestVersion: $(led_latest)
              modulesPath: tutorial-containers-03/modules

  #! Build stage
  - stage: Build
    dependsOn: Prebuild
    jobs:
      - job: build_led
        displayName: Build led module
        condition: |
          eq
          (
            stageDependencies.Prebuild.envprep.outputs['led.doBuild'],
            'true'
          )
        steps:
          - template: ./.pipeline/templates/steps/build.yml
            parameters:
              moduleName: "led"
              latestVersion: $(led_latest)
              modulesPath: tutorial-containers-03/modules
              pipelinePath: tutorial-containers-03/.pipeline
              registryAddress: tutorialcontainers.azurecr.io
      - job: build_button
        displayName: Build button module
        condition: |
          eq
          (
            stageDependencies.Prebuild.envprep.outputs['button.doBuild'],
            'true'
          )
        steps:
          - template: ./.pipeline/templates/steps/build.yml
            parameters:
              moduleName: "button"
              latestVersion: $(button_latest)
              modulesPath: tutorial-containers-03/modules
              pipelinePath: tutorial-containers-03/.pipeline
              registryAddress: tutorialcontainers.azurecr.io

  #! Deploy to devices
  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: deployment
        displayName: Create Deployment for Device
        strategy:
          maxParallel: 2
          matrix:
            #! raspberry_pi:
            #!   deploymentFile: deployment.template.json
            #!   device: rpi
            #!   platform: arm32v7
            jetson_nano:
              deploymentFile: ./deployment.template.json
              device: nano
              platform: arm64v8
              azureSubscription: "Visual Studio Enterprise Subscription – MPN(/subscriptions/1ed39caf-70a4-44b7-86e7-dddbf04de6f6)"
              iothubname: "kws-dia-iot"
        steps:
          - template: ./.pipeline/templates/steps/deploy.yml
            parameters:
              deploymentFile: $(deploymentFile)
              device: $(device)
              platform: $(platform)
              azureSubscription: $(azureSubscription)